---
creation_rules:
  - path_regex: platform/(secrets|cert-manager-secrets|external-dns-secrets|observability-secrets)/.*\.sops\.ya?ml$
    encrypted_regex: ^(data|stringData)$
    age:
      - age1aywe3xdhfuux5lk54dxxvhnfyxcwjyhv573cnd2l9gp0axn689msthmd7r
      - age1h2kyl30pm90tkdz20ertu73pf94chkvfj44w755uzz7vswzqtq4s0vxgct
