apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
    annotations:
        platform.garys-lab.io/plaintext-sha256: 845bd94c5d1afca458c3ca09eef5d9d272829f473ccd7b565f57331e35123138
type: Opaque
data:
    api-token: ENC[AES256_GCM,data:H8flaFQgApIT43Wik9fZ+xnlF3JHxC5Wvoml0u0Ryna5TgkEvuH1ytDM0LMarSvappj+neK85scOlvi9T/Jc6PbjPMQkCJWf,iv:9rHeZ2BRP9WE96mAxiRtW1knirtcZiEIxBh0slCUKvU=,tag:WP3lx1Xr8hRkoKILiF+Psw==,type:str]
sops:
    age:
        - recipient: age17ru9ns7l65qdca574qd8ve80czz48cvjjd4pltcprfp0ptdefvwq2t62kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5M201YzVGUEhoL2xubmVw
            amIwUDhCWUlkam5YUTUvUHdPSmkrYkl3dXk4CjBXQnFqS1hVVFZjaVlTMHQ1WjBp
            M2ZvWnNDckJsdFQ3TjJQckZQM3VaNEkKLS0tICtnQm44RCtGbW41UlhRLy9mQWJJ
            TWJLdmo5SHdxakhyUVBQdFhLTU53b28KHSTmka8f6cUS5nOu2Uv8O3GcXL6LEt7t
            PlMTrjscKeoSp430iyLl20zdhVg9W+w6BzOHaYN1BSlRq9vEdT0BJA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1h2kyl30pm90tkdz20ertu73pf94chkvfj44w755uzz7vswzqtq4s0vxgct
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpV1VhMnR3MW1YRDgrcWJr
            ZkFxaGp6OStNSy9vc0JsVUExUm0rTTN2RHlFCml0NkNkeVRQbjU4eTVsZlI1a2VJ
            SjFLQnQ0MU8wUWkveDFEVVBRNkFmSG8KLS0tIFF2Z1dFRURpTXYyUitDdG9LVG9Y
            cFo3WmZXSGxsNXlKQzJVcjFQemczWXMK9/bx1Ae5mcoeTCOEHSht2rN+y/IYJArS
            0tF7C8F1grIIbECgnQhb6SSKgtHN/1AGIPUZFUASPcpi0oVFIHCLVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-09T20:54:15Z"
    mac: ENC[AES256_GCM,data:eyK44Ej+YQjw/XOOt5aSRDsY7tKUHTFhVwJi+CmE9wLhdxsu4mDWkymM9C3kDocbi76zd89l2dN5HZ9/63rVFHGQfXkF44VxPa4GfrXj4Q0y4lmWjteSJ+7mlo7iVWH7NviYMjTQ088fYRqXYykcqBZKK4+Lt59gVIEBfQDkcF4=,iv:KQcvv3xoibWYIZCfm9OFgDgDc8VnURqkwMnuRTKuB88=,tag:rwq0wo9D4hLq0upTYrSe3A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2