apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
    annotations:
        platform.garys-lab.io/plaintext-sha256: 845bd94c5d1afca458c3ca09eef5d9d272829f473ccd7b565f57331e35123138
type: Opaque
data:
    api-token: ENC[AES256_GCM,data:QEq/kXX69grjQMAXWb71lZuD0drNcYuier3ZJxkuDgT2JW833svRfbcEvSKUVYJIt5SRYQlmMRuO8eB10Bm5LDp/qkwyXyXQ,iv:fAO6Ngt252qNa6oBSLtqc7H3ntz5aVJsKpPXzByia9s=,tag:a9ynoUjDJckLsU+mvD3HgA==,type:str]
sops:
    age:
        - recipient: age17ru9ns7l65qdca574qd8ve80czz48cvjjd4pltcprfp0ptdefvwq2t62kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1UEoxeEpzb2FXZE0wY0xR
            WUd1VmliaEdWdlNYSzYxOHptdExLb1IwaVZ3CnM5ODZtWVk0RWJGeE8wK2NaK3Nw
            emRmRnlQSnNVaU5LeEpDZFhNVkt2blUKLS0tICszaUhteHVlM2I1aUFsaHVJczVG
            MG5OUDM0WTNuSStoTWx1TC92Ym42aHcKnsw2z1/wxX/pKrTIxPsgEBXMkW6Qpd4i
            vVEzPpiQwrnfb4oWl4HhbBsiiLx/KumN9+R0Nt+X+uDM3QCTrOtr2A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1h2kyl30pm90tkdz20ertu73pf94chkvfj44w755uzz7vswzqtq4s0vxgct
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKQ0NZbHVvZHhjZVBoRjJN
            V0c2YlZxcDh4UkhIQnByTGc2NlVPS1lpcTBJCis2OGVYL2tWQkRxYnY1ckFER1V5
            Uy9zdnR5U3lUeDJJNTdLK0QydlpNV2cKLS0tIFZaRC9PVUhRRDd3bmdxNS9MeDBy
            SWU0TEk0Mm1YbWpMNGxaZFEyS0dqbHcKwh/tlfMcINTOgrozdzHqcNE7xvzxqxtJ
            1ODxaFdX06WYjqFP8AETk/jH/DeisxR4xGo+Nic6EKr71AoSL1+Bsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-08T15:52:26Z"
    mac: ENC[AES256_GCM,data:FqNP7G6qNDAkob0uuPwNxEP85TGQ+KRq+V87i3PvvVdcVK7k04S2B4+1qqAjkQlFQhSyuKQwkqTXa1OT2AxQurB/vLwnrIvt1y5Z28nooq985ptDyvvGdfW9ki3v1OCPaT00Osf6iVKe1A6TKZGD39v3JbvCQaMjBLXP0/fkUBE=,iv:+RX5SbzroNsMa54G+jBCfNkblM6QCr7d2tP5P6mIH1M=,tag:UMvXwSu9nyVjmXK95AZBzA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2