apiVersion: v1
kind: Secret
metadata:
    name: external-dns-openstack
    namespace: external-dns
    annotations:
        platform.garys-lab.io/plaintext-sha256: 3a228fcad92385abccfadf5dfefc0d8f280afbf3714415a2baa7002220733036
type: Opaque
data:
    clouds.yaml: ENC[AES256_GCM,data:xt0NZOIsKV/Yu7yRcnyf8fkLVj5xDg/x1NrdmZvJGZOGEgUDXCG3qvht4Od3nqgpjwDZ4lT9a/9UHUZgWRyBrLd6/5pCeH3rFpsnohKUiEEM3bS/WZdAxnqqOD/8r73qeBZqpyn20jj1qH1vamublbtWpYCjkJWqvdMHZZxSeDhRPGVsXmn9wVBQbHlXYa9zuGiMIjOwzMnChhAVMMH7y7ie4DDLe70BfjYD6g290AjSlssEnlhA3slgqxQ4u4ezo5zDThMZDLh/ud41q+jVm1DoofGtF1zC4IkCyfK2FgdFMFLMd29X+B30KORCJG+/u4eOYSGJm0CzvlRiP7tlQm7hcKeN0+SfLwsCoClaGgy/OvpjcQHm0pGT6JY/J7fSHHeuxV4/pPpE+O0UAmzMbLotoX6AatxNj4rfMs/EpV4dACgM4PxGpnrVP4icCKkB1hXWJvRttM8xummowzLdhxg7ZNkel4Db7fXh5P3VWMU/TjlQeW29CehS1+f4JOFHfFcrTnKMJUvNZT6gklvW9O2L+fhKIdK3cx+7WPQ4FF1Dk10pV7epzuu1Uidq52DFB1mAcb6iHSzPcNfd9eM3QDBEOqOhOnIZXH5gZU8QPrvxZt6MPpPsPr9+APUZwum843oKG2uYArr0nYNifGTXayAInIeBrlzi/lxSvWRwauutgLkP4l5wDwwvnyBtdNj8j8q2XlgdMQqwVy1ALdHcE0sWfkgvlAip55Jpr2HXWYdU/+bvr3qlXUZnxZo5aHu2sfcJKUMhW8kPaBCpcXqVwoaVsO+Z7bA6k+c+9edF7aFT/tB1R4UE9vbH2rLD9eskPLRinI65HJLgbL55tfpfZ5xe0LpPK7Put5sKbEG2DpKXvVOyiQMkFhX+X9zQBQrQKaNTgQ==,iv:HqB61+LRLU5qy+1Dl+zlty+3up0so5X9HwG1FjVB6NM=,tag:CWolgzjajTaVwdi6+Nih0w==,type:str]
sops:
    age:
        - recipient: age15zxr0z8cd6dqzqh3g7f8puzqwgn0f30qgrwfx26c32wljlzr9dns0ejad4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwcGlJeUw5NnVSdFh4Mkx5
            NzlTN1FxVmJEbHpyT0poUDFaVGt6NTEzdDA4CkdzQ1UxV1QzTjZuUjlaOTNhSHVX
            emh2U1JzMVdBRjZycFREL3dWL0U5K0EKLS0tIHcrbVhvdGlQZzZPcnRWWkUrY2FJ
            a3Z6UUdhYld3QXRteTQrTUhuWWlod1kK+hQYYCqmlMFzBTzAUU5hJcgZkDzFOej1
            iCa8L0x5ZRL54NxPb7EAoBb6mkj31qkLxQzlMO4u72VRt/iQCRNCxA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1h2kyl30pm90tkdz20ertu73pf94chkvfj44w755uzz7vswzqtq4s0vxgct
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnTzBvNkpPZERVajlQMWZR
            Z0E1Z2MvTUYyZ3hGU1dPcC9nbXZQdVhEREFnCkhvV21OY3hMcGxVV09ZdTJUaU40
            eXIvQW5GYW1NRjJNYXlLMlg4U1ptNlkKLS0tIDZ2dnhKWXcvTm1QMGpsNHFLMk5t
            U3hKU0VpU0pLRFkxSklBcno1Y3ZhVFUKYc4lBZVgb4qdnKG96SjrGl+25AD/nbqX
            z6QYKqX8+wKm1WnxJXAsV7MSJAsCbP38FFIBTvl35M0a6dbUiwzlRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-16T18:33:40Z"
    mac: ENC[AES256_GCM,data:38go3yhexh2VWdkTHmkGvobhfG44EvN03jVx3IA1p0gh4np8enDgJu3j0DtlpIlpkfv09ob4P/NoS+CtRLzx+pldTN51VdmFeVC2GrVOpil7F4lqvQxxzWD8+b66Kxv7gFztX11VN2HMnkSxNWaiHjWPBRmuh1aaqxkSjJozwAQ=,iv:elbQCwoEwwY1ztWLBIszCeXmiZnhjFSrGB3cq4DdKOk=,tag:wlfVWDft0UPVkUrWaZOXtg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2