apiVersion: v1
kind: Secret
metadata:
    name: external-dns-openstack
    namespace: external-dns
    annotations:
        platform.garys-lab.io/plaintext-sha256: 3a228fcad92385abccfadf5dfefc0d8f280afbf3714415a2baa7002220733036
type: Opaque
data:
    clouds.yaml: ENC[AES256_GCM,data:jOzdZs3cuRYS1IvVd4eSzYI9oL0U3oMAsIRK9WaJlN43YiA9EM+0f32JhVHnfS8U6kBE4TVXgbwCaeDrtKGgC0SQ/iIp4jNiijvapcnPY6GM9XBx4lhczqOvEMlwsKbnkEZq0dxVWLhKXN+ZVBQWV4qn8f8PWjojbaKNrca/nFe1nI46/e+ojt9HFRApGahI57MhpsCZzlbI2ZC6K4s/TvRipaKoO7e2cBqCcTueVOFocy1RjPCmYxkXL+EKQQUa+zTxXChM8KmXqgk1IYLN7zc7z8+0hV+3dQQaqPZTe/lOeWKigWssGOUv8NiDf+aTQJQdzevZwIIAcgVjzln6zZ/dDghbQygNz+NO+Uabcw5Mzen03/Abd56Biqz75ta0Z9vpWXxXILvYIAffmmmA5PdCc64JxpohIvM00HWaIy3+vuIm24EQGRtWuUQxt8I0SvqQKKPywv7tGhoq2NW2QiNfksKdj1KrVMKSiBi/utcenhR4PBwevUc8sbo5TBXV6Mx5rLGaYaF831elg9edhuYMHiMAhKpxm8dyI4LD8IJQYCT2zo1LJSsu/cbb4dHYAmaDeuYNStelolI8gx8bHGMIZfGGjgUC/fQy21aLG0byZDcJ2zESuDiwGJaJFt+zpnUfs/DYKzdBqRyPNmVh0BrWnPbmE1eYGadrp+kiBOU9BLKeAb2uF5i7U6LQYKWNCdyKJuLH7xCG5sGamD8Q9qJlpOrgFJ2fxAbETzBj7SqWLkI5D7OAiiJJ65tQxh+uadgje8OlUr2UpR3pgwoJVf3j/1vvhT6ZacgFh9KHfp0M0Hvrbrf8ZaIBJ7D66FUd1w4ZcK2lh5lwvF7cLh388EavOX80Ayho3l9Il5nZDbib3mEDzrqNyGXHhK9fpYegQmH61w==,iv:5qDZxov1e9Jh7pAAsNJ9qkoHLFulf/q7+FwMFA6o/zk=,tag:6Ix4RYFQOZzJ2HUhG78Yow==,type:str]
sops:
    age:
        - recipient: age15zxr0z8cd6dqzqh3g7f8puzqwgn0f30qgrwfx26c32wljlzr9dns0ejad4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLNXFFSlo5NW1xMlNqTGZy
            RWxVWEFCQU5VVDFTZWROZXB1ZVpZaW0rWVRVCitvVFA5cWR3YXhFVXJJNHdwOGVH
            Mk9sNXNkZnVZTU9yejV0VnMyYmlJTkUKLS0tIEZyQnZvYzM2UnZuMWsvY3QwbDFN
            ZlhOYStBNGo0TTBYeWJ1K0YwU1c2RGsKwDKKV4NO8Co/KGwqcKZYAAz6NRu9JGBz
            IIRPHLmAL72Bsg8CBTWkI0qRbkkPKAZDvezFk+hLHYDLv2RJF+azGg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1h2kyl30pm90tkdz20ertu73pf94chkvfj44w755uzz7vswzqtq4s0vxgct
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXTnJSTTdoV3EyWXlTeld5
            bmdoemxGeFlTQTRTKzBKK0pTN1JDU2REMjFZCjV2N3pOVEJuc01WY1JGOFhLZUU1
            R1NsblFIeklGa21CVElMYUo4dFFxVUEKLS0tIG1yTjRILytwaXZZYW8rcDFGcGJv
            WWpCSGovcGZlOEUwV3o2ZXhWTk5Rb1EKrFuNlimOdx853a//kolzvAgG/bTUNri0
            Uqph+ZhIho9LYNriFeg6Jo4fLpIIQsHODLKScqXyVUo6qTHv6oVH9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-16T21:41:03Z"
    mac: ENC[AES256_GCM,data:oa1eEzQ4vDmlG628x8URaItF4a79FXMz38Jld0GiXzakc+Ym74/cn0EqtM+EvpyZhF41na6E71vbyUI2xbRKwtGf1BT6xEFfqtfl7yhK9C/6gDGyXVUEVC8no/f3uyjsSZj+dv3QoG6JLouWjC2RKbge7V+cR/cY9KKBpLwGHvI=,iv:VMQbujFEAR743wnO9D7i07mLOZUvY6PKuSYwcEJC/u0=,tag:S/2a8iRErohLNpxx/ItCDg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2