apiVersion: v1
kind: Secret
metadata:
    name: lab-ca-root
    namespace: cert-manager
    annotations:
        platform.garys-lab.io/plaintext-sha256: a5458ac79ec28919c387f7927b962ca8abb0d9cfd6ffe099d83155be8be0122e
type: kubernetes.io/tls
data:
    tls.crt: ENC[AES256_GCM,data:cCyPDHy5s7I2TjPEhEG/mAWuHx0+lwstFXUvSRDi0mHlDWpH1+ZI2Ok9YJOGdRaMlxWbk6/gtGFFDCEptRD+YzvmYaNCHmKgcKxsOmX9IS9dFIt/PRIoJMEiNbvHEaU/CHUMZWx5OJcTBLuSJ5zt5klcXl1jSpxUkc1OjXTNIzsThAYssGKoZEuMEheRPR2paxB/I4QRl4MzAJSPI8RjxCTNEPXxO6CWWQV8KrEyA8EeCsAkmwcY9916z37Ri5QhG3Nxxjq/yVAw968XlafoX1u+ppQ0eDDdyTbiPizh6FU7r4Cid5rS/17GhbqCGPMJ0o/vrMRewncNo4B/PmxQVbGhVfbB/CyaxN41Wa1wvncu3og/fqWsMb3z0TDTvfN/15aoa74ZyIkftnPE3M230xgF4QAScAw0I9TmhwpVxXpAqy0qSPBwWmg7hZ+B/v9c4I4jq2bQz5DvXNvwQsQf9cecG1RCIpe7uX+jC/xcUz4qNiFaW85oSSRTJmBDZjhAsaxR43NMSEL0es5hV7HPo+eD+bovChLP35Pfim6EK7xFHXFaRGKTH4PIzwG4HeLH0g5bqJPHkM3DJcLPZkY+r6O9ZRrf/UFiaOf9JQgDWiFMpTY8allRwN7IheTvhl5IvWXDs2C9DMK2Di1uovxdf7BYvVCCnmybaU/45wwmbJXOcvvEiERuPePrAPFcELkr7PN9rLKooItCh42A3G0DWUhRHZ3icQ0O/ebH5L+nqXF+zA04L5GckgmwnvgpM6f6BnyzLkTNQIAMxMexKoVWnBovxF6fbLMk35MDGxpwoRwxOFgaOf2dk/3xEEiHjmLNMV7BanBiaLQVWFoEaCaXEzwMJKtAWIUhwwsjfjupRL5tT4thlIsXqdUaEaEcOhTqunGoQmDVJsJivvAYN53VDhByx0wRy1UtoUPaO7CBZdd3Y4K9xEB5v2JTGWIXVrdHIzQoB1IojgqE7UokDGUSc/vyWQLa5kaDkGwuqL2lsCxwltBomKCTmtG88vUhnleL8ob2AI+2RL8HbgBFqB3xc8E49N/bPvBgBkRtRVQwzzzvQUnsbb5ok0iekL/M41T5QIdLPS3hS3APq2SrjuXnyRPO08VYs9tR,iv:PMYrWJAr5OTMFRYH59idY6Ka2XQF13vl5x475bmBRJo=,tag:KDVqMi4Ey13gCRply3NYqg==,type:str]
    tls.key: ENC[AES256_GCM,data:iI0txxUs2YUKAbgWn70gkfvjxRl1bRFKm150jzJjEmOUlKnGL8ORBYtbJsKvYuX47Nf4mHQFukzqNw3Yw5grj1/I0QZzNYVG/3V0EpjdRAxFxhFD76yU5exuDrMPbXfVKjf0lXF4j4WfFS7miXp0oGbDMuBwtKetRqSxioDXPqhyHzP3+zqcf+vCgAs1CmBSfbUBw68OzVzQ5IIK9dYHQJP7hLKjDBxADCyNdUQI1VoYvArrj/gJgt42RI7ur5I6ras7JB8yXXhSV+wnJwNpztFkj1WeIVwx/VohiCzrBAgsXzvbuC6KhNrC9K2IH3avtBK5gt2Emg52Y5ixKAgLzmNJd+NFx4yLutsuZX9Zuqp6xGKQhApXpwTgTKT6slZWXWm4HDPzHdbzbg8QjOqu4yxr1pkqwflawDkiHwjUob0=,iv:+mH035C5SR2+8vE7sq+S2M3bfJxwvyTrjjAGFzUM0wI=,tag:yEKY2G2dt3wLXXDugSlKTA==,type:str]
sops:
    age:
        - recipient: age1qvrrx5vawqay8rvtna2v8e4une53d7q88gthen6gmz9796wggaysa8nwdf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTcERKUVRoV24vaW0xL1A4
            WU56SGtnY2ZJczZkVWorWm1teTBOL2dLa0NZCnIrcm9BMW5jd1dOalMyU0VwK3Ex
            ekxJUXVSQkxTZS9nMWFHUnJqeUdzeFUKLS0tIFNtOHp5TXR1cnFGbVZSU0hJOHpl
            Tk00K0F0c1VVU2ZBeVB0dkpEK1VJUlkKGkrB7kiWQwpeaOoX7K2FExR8tTE1vapX
            f7UGh5YRrB1ereN6rTaQ19qmgWCLjh/GocYew5EY7Tc62EMrGmWm8A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1h2kyl30pm90tkdz20ertu73pf94chkvfj44w755uzz7vswzqtq4s0vxgct
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4MzdwTHRrc2wrVExkdzJ5
            elptcXBJZ3ZJeWNVNncyaXRCV21oM2ROSkhnCnhpanZ6b2F5UHNMMjFVRlArUHN3
            bTRBZVdLRmR0RTFxYkVMVjhHVldrQVEKLS0tIElkYk1HaXVIYWdhTzkrSWRHL0lT
            YzdXM1Q1ZzcveUV4K3BxN3IwOXV1UXMKWqslt1d5zuR+5KrywBnacXfVbYIO2XND
            tDKRMqeS0s/08bitGD5ZRUYmBGwH466rZ+6Ec24pY/4XwOBWLDqw+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-10T06:27:01Z"
    mac: ENC[AES256_GCM,data:ZsHjhzRTkc9wBb2n0yFBTv13NlM9w2b3SpbyaeauPqy4/Aw9zETWO2ImzMWeAyRiJc0URFijgT+Tmi1NpxvN7e0iPNgDf4Esmd3F807yvlhFmdv5eSDGxNKX1GGs22C26mFB86GEdByPz5bWh5V7DITsmy+smpYTMCCsuvFvdY4=,iv:TdWEJQ1D8XIvw9+zqlbuYEFMbyVeiPTcMuIyLU/juSY=,tag:62afIRdIHptOEdtLTGipiw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2