apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: observability
    labels:
        app.kubernetes.io/managed-by: flux
        app.kubernetes.io/part-of: grafana
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:AniHgQg=,iv:aYZBjJpGG5zi1b/zUg2sdbPz3yp1KNrXsCu7b33No5s=,tag:8HV03imWLPW3LBMeZ/Hs4w==,type:str]
    admin-password: ENC[AES256_GCM,data:FByqjWd93Dm2aOaqle6qJjK1VhYb2iVdCW70f66tNsX1fQOwtFoot44t+dn6KmcF4ZAegcg7O8iwv9VGHq/g3g==,iv:rKfmoNmf6fEeVKwNCXq8CJu6ElLIBDLhc6YWrFNSBCM=,tag:iYZPqzSgOx1Yffor2U67qQ==,type:str]
sops:
    age:
        - recipient: age15zxr0z8cd6dqzqh3g7f8puzqwgn0f30qgrwfx26c32wljlzr9dns0ejad4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzclVwK1FETVh0QTZqb1Rw
            WEp1SUJ5RXlmUTM1MUNIdEFYbTlnOFJUREg0CkVZVlRGWXdiZ1BHQUFQRFRhU3ZD
            WWxSWHJlMzZkY0FFZEdNYThzNWliVjgKLS0tIGNoZHBVazEyOEY0MFhIcTJubFlu
            ZkwrYVNkaHhPN2tSeU1xQjVvNER1ZjgKjC2heSA1P8xgQz++0eDVtqEF7EtnqwCq
            UbjopOSwljb5V3V45BRKX4ASsSmnPlnLVRKDtn245809h+OQnJITkQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1h2kyl30pm90tkdz20ertu73pf94chkvfj44w755uzz7vswzqtq4s0vxgct
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiU0Jub1h4ZS9FbTE0VCtn
            dnBvRldYTmxYQklOUDByL00wV05CbWRjbENRCnBkV2ZBdmtRWE5lci94NTFsQmlh
            YmlQbnlDSmM2aFRKKzB2R2RzL3loc0kKLS0tIElxemxvWk81a1AvU2YxRDYrTGh6
            a0NnY1pHUGxpeFZkaHFNaU83U0pZeTgKIQMVThGXk0pkrp2aAeAyqzVk58dw2/kU
            gNxUJ+afAHpCPdqHDSTIjtJ6GFnS8g+nML0z4WkJG0I1eY55aroLLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-17T03:39:44Z"
    mac: ENC[AES256_GCM,data:mpcREgZg+dXuiS5NbMFvtatgmHh427Nc5j5BQFHfKLCZaia5vmxQo3gN1H2kgze7pUi0Dv9uyXhrEpcWKljmKO4ybVPnD9NZn6gcCt1my6Q7qfIxJiHf6oFALcKzeW0s223igCGtyrWcRN4MB6tQMkNqLXcd+y4d3Wt+YZ4a9Cg=,iv:jCEe7rQFYU2mymoS4qLTd9TO25Fn4F0sddOoGqq/S8M=,tag:JcMeulWNRBMlst247bcQEA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2