apiVersion: v1
kind: Secret
metadata:
    name: rustfs-root
    namespace: observability
    labels:
        app.kubernetes.io/managed-by: flux
        app.kubernetes.io/part-of: rustfs
type: Opaque
stringData:
    RUSTFS_ACCESS_KEY: ENC[AES256_GCM,data:TUaa7amc1SEU982XmxABU1C4iHAm89eg93tYfS4EAtE=,iv:SOFmBjFql0jDpBpyE6O+tRtQqxOD377UD6oRZav5IjI=,tag:6eoEW8j/jbnEV/5dJBTjUg==,type:str]
    RUSTFS_SECRET_KEY: ENC[AES256_GCM,data:01i9EoUa7gkS7Hcny5OY/NXFZuh7c4DrXSj+P4MiQ0TVLsa4EqsPcX5q3NY=,iv:oqs5r3l8RUSPppWLvX9p1dbR/Zir0sHov5HWVi3C6q8=,tag:J7im7l4KxDA33WhRvj3+cQ==,type:str]
sops:
    age:
        - recipient: age15zxr0z8cd6dqzqh3g7f8puzqwgn0f30qgrwfx26c32wljlzr9dns0ejad4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBneFJSQVBYREIyRXVpaXdC
            d01DTWdheGoxdGdXRytCTkpYZ3VsSzdHMTN3CnpCa1M1dVRkblZzYjcrWU50N204
            dlRqd3pLdXZzUEVJOHhNakZYSW1GY1kKLS0tIHRFWkt2anFVYnNiS09xQ2ZkUTRQ
            MjBPcnhKNnRXOHJBRVQzTWs1MkxOOFUKzuKqyG9pZgzSsVMcwQnkc3RSgZ+I7SJT
            ozp9DyLT+OltOhn1UpRf8/G/uwIAJp7+exMhYZmDOiX6wD4uualxsA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1h2kyl30pm90tkdz20ertu73pf94chkvfj44w755uzz7vswzqtq4s0vxgct
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOT1kwWTlxOGtOcUtxdEJH
            UnRzTkpUUTdiRElYcW5ZaUxLSGZ1aEVGbWxjCnlXRGZoYnNTQXBicmZ1Qk15NW9r
            QnVTWTBrQnNNVXFuakxFK2E3QmswVHMKLS0tIDZObGRFcEIrc2tjVEtLc1Rxam55
            WkhRUkgreXYxRXpUNnZIYmptQ1kwMXMKDgeseMTqtxcjo+/s0XgBcUf3eDaVzRRF
            g/dChs7zynf1svEGKvF3zu33/5fafmURDd3PwtVH0rk2A3yMmAw/TQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-17T02:58:45Z"
    mac: ENC[AES256_GCM,data:5qdVpqfayreVXmCn0r+hwWoBELUk4yNzlZoBx6SB40v8zX6IFHKsvZUt1tdgjWfu82DvQptJMMs77l1dtjk189blAsLsq/E4VzIQwsRKse4/u6tlu6R5mbQl8PKh2PM0fJS+gRX5AuVHmw+IZnL+os8aZR+VZuzsxqi7vG59Alg=,iv:vKKRNbF0AOTCgjiPbaWIjOnLNGZbpUwwzAMZ8ZsacTo=,tag:pzNu/GT91vUR4Vwrt/xvcg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2