apiVersion: v1
kind: Secret
metadata:
    name: rustfs-thanos
    namespace: observability
    labels:
        app.kubernetes.io/managed-by: flux
        app.kubernetes.io/part-of: thanos
type: Opaque
stringData:
    accessKey: ENC[AES256_GCM,data:8MKL7zqIhK1CFYaPUfPx53+KwLchtuxFq5/6CCs/H+E=,iv:nlTbbhUIbKkWsQJqme9UtXNs8WDNPvNXZqBSCPcRH6A=,tag:0pn7QQR0cKUPm0AhVs1iPA==,type:str]
    secretKey: ENC[AES256_GCM,data:A2l2ZoTjfVVUZB0B6DFsu0fvYuNWCiZcNBhMN0IUaob9ixQbFB/CGA==,iv:h5YzV8mLWSQPmiy1k7b3tM7A0MP4tSK3T5kAD8ldMkA=,tag:1GvfPqlydRAKBx3c8ssd3w==,type:str]
sops:
    age:
        - recipient: age15zxr0z8cd6dqzqh3g7f8puzqwgn0f30qgrwfx26c32wljlzr9dns0ejad4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvRlVyNEFDMkVER0FmcXR4
            dVVSVVhJNURRUGMvQmpkUHI3K1E3Mmh1Vnd3CkRyazhzbVF5cUZPUU9LdzllcWVU
            WXlVQWhiVjFQWkpMeUpwamxYeFQ2Y2MKLS0tIHFPNDV4clJvYUJhTXYzN2pMdGJ1
            OVpNUGtVa25SS2tlbjFuRktxUGV0VVEK8EMs35bzyTffo0le6PdmZI/llOtfqcxn
            yQML6n1Aes2hhZvZwGNFT3yIO3NnCkdSiVyTLGsyadni2/zZrvqK9g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1h2kyl30pm90tkdz20ertu73pf94chkvfj44w755uzz7vswzqtq4s0vxgct
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBidVlqS0E2WjhsSWphY0Iw
            M1pVMjZ4NjM5WGRvQTBRT1BTNE5NTEZUbERRCnlGc2ZTdVV3OGx4bU43UjFiMXJM
            TmVqQmlFcGhxQnNEZGIxUzlDZ3N3Z2MKLS0tIEVVV3ZEYmI4UDE1dm1MRW83K2lO
            bm40VjJyeWVnRm1US2FEZkdmTGVyUEEK3iwADvbJExTP/0zs6GbwT/OdG9FTzQI9
            etMZKz6UnU9OThexkONhtMUUcci4kp3sQRSv0y3+H7yWu8QSLcgEkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-17T03:12:46Z"
    mac: ENC[AES256_GCM,data:bLmzOaIOhbOMtDZ6ajajjKIVS6MBINzArrl9uIuC8RaI0DFxlBCc4Tj5GKctUoig/KQeUoYFktipsIL3kU1XdBG3dpFdneM+yhsPLHLrmjOH98p6u1q8RYgEvASnDw6bmCgfDmm0E9Ib1CKm/EEK5n0gJ9eDgEX4gd9QgzfZLpE=,iv:k/BV6UV2tZwMyMbn0/k/h+qVJOxZqOP1qECbFX3bXSQ=,tag:nVIBdKbXwTx4Hao6l01LrA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2