apiVersion: v1
kind: Secret
metadata:
    name: rustfs-thanos
    namespace: observability
    labels:
        app.kubernetes.io/managed-by: flux
        app.kubernetes.io/part-of: thanos
type: Opaque
stringData:
    accessKey: ENC[AES256_GCM,data:W0C+PX10fAVELhfquUGNrSfYEH2afjKvW4jXOfw9h/E=,iv:XgnN1X9oXbwRYtOkX/wTFPZn0VQBssb2VOxbPnmVwLw=,tag:XVkfkia//q0hEh4M4ZpMuA==,type:str]
    secretKey: ENC[AES256_GCM,data:kaq3+7LydFPQH7Xc6cxrN8VAZ/950HAbb3TfitqTNhFdmn9Uo+qVsGoAgRY=,iv:qvWTc9CCICQcUiqijqZ8liwHUjgOcZ4nRy9p8AliWUE=,tag:2bY3o4YipsohD/77Kfp0SA==,type:str]
sops:
    age:
        - recipient: age15zxr0z8cd6dqzqh3g7f8puzqwgn0f30qgrwfx26c32wljlzr9dns0ejad4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwTkZWb3NCUnQxS21mb1Jv
            N0tpaEtST1pUbWtVU0VyTG0xRmg1Q3daZ1NNCkoyT1hBdkMxNjQvSEdpSGJwYWs1
            RUhEeE9lRnZHM3B5bk5iZk8yVXU2VTQKLS0tIHFzN1o5Y0Z4K2dxTEdUSGNIWk1L
            N2ZmUjZKTFhDaEFoOFhTenV0YnBzUEEKn3ShRIYUtg3kesoWgp29hE4CCYneCsGQ
            duDTFRJ5jQIcVtzdGq7faZHz16befCAtAibcbNXoV9WzJ8C+YzaqWg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1h2kyl30pm90tkdz20ertu73pf94chkvfj44w755uzz7vswzqtq4s0vxgct
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1YlpTeVZMU1NsSWswWENF
            T21rcnZjWkJhZTBjcjlNWW1COTlHcmcwLzBBCmtPK1J6dUM3VGZaR2Fud3NpTlVx
            YldGTkREbnJnRjZ2OVBRVXh0VWlsM3MKLS0tIGRRNTBrWHlyUnVxRUJGMFowY3NM
            SmRvaVBNbkk5cDZVcWlJWnd2dGRuWDgKPFWKvhOzceT0X8Dphiy+t9nZ40cSDcCO
            Ip+zYEj1vUUS7TIJ2LiJCUwqd05rjQVEfpWfAQnLENdTDXrydT6vtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-17T02:58:46Z"
    mac: ENC[AES256_GCM,data:YXE877cDeya/NA5mzBDzzcJO9TueLPteUqdtx35lECMJowKpS6ypZOkidcqQHA8STs8PBxl+xcpgwdUOo3T+9BAvXbGsblkzWjiO13yMSK+g+ikyPva9WcxJ5vyXsl4CTFHdYYfwY/ZML9nLBYsHbkbCYoXpGJWI/dNFyRNrRsI=,iv:a7WGRO4yBhovrB1CUUXBKH8SiSOpAq8pMNwB/IhZCtc=,tag:3n+BYUfdBPXdHClxthKBYQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2