apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore
    namespace: observability
    labels:
        app.kubernetes.io/managed-by: flux
        app.kubernetes.io/part-of: thanos
type: Opaque
stringData:
    objstore.yml: ENC[AES256_GCM,data:6KCk0UsPYISKSQyzKDRdDsqc+PFO5t7sZAnD9V4eBY3K5KXTmnOe/HSXk3e8SLwnqdgY4pM8tWwbLU4DXESwvfcoQWKBgdntANpF443o2AaoXKKkFMao4SUsevlJ5IIr8VeSicNGR1ph1mP5uUbBJL/KJH0oLEijGSLsR6+3zys8b9mDSAqUS+SOMYsXyeo18dWsa3tFQCBM2PbNLhivOLr/vYdJ8+LYs/U0GxKy3Ehm64B0HMD3KeOm/DdwasTUxq1/fvfzcCSE6f3cVm8PvxpUfjrE7gOj09GDbMSGuL3Yb6ZZCg==,iv:H05Xzy4fz0l9pmbYnWzA4XUPtY0YFRff+EgUNlgxmvQ=,tag:nWSe6cKTZiOm/OChHtmUmA==,type:str]
sops:
    age:
        - recipient: age15zxr0z8cd6dqzqh3g7f8puzqwgn0f30qgrwfx26c32wljlzr9dns0ejad4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkRE1uZ1d1KytGS2JGaHVL
            NSs0alpRbnhJa1RUVUxXOEZPOTV3bEM5c1E4ClY2dHcvL2pwcGg1WkpBeGdHZlNp
            L1NIUTdJVnZJYVhYd2NJRkJHZkNxVEUKLS0tIEFXbkZ1L2R3cWZmdjF6TlVXMlRG
            NlJrY0VuWHc3R3RuY1lRZnZzcEdmdEUK2kmIYNY5wV0HAB9lx6ZZSEY12D+6BAgz
            PabMB2c0QPLy4mzHCh93Wq52nmYnEMKjp8dZMOAAiGYPlhC3dXk+Vg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1h2kyl30pm90tkdz20ertu73pf94chkvfj44w755uzz7vswzqtq4s0vxgct
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMbTJGaUZoQitiaUxQem9N
            OEpuRktEdzNEODh6VWRMQ0ZIY1lhS2tPaHk4Ck9qT2d0bEtEaG1EMHREdTBrQkQ2
            UXBvYmFVck5UOUxPd21aR0pWZ3E1VVkKLS0tIGhZb1g1U2JFekRtSUhyOUJTNXBS
            NTM0ZXY2eHhMbkNpL2t0MG5sMTlTVkUK2SAXoVD/8BHldFFdnfpZIkB6T3DRPDrz
            5yo3CZQhRjbsnR7Lm9+lh5eqAz+l0plRyGgQSqlDS5498cWl7419Xw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-17T03:12:46Z"
    mac: ENC[AES256_GCM,data:CKrdSAv1YwTbpQUfiZite5giyazl7hBHYxv2LTf/LGNf0y2PgLiBOQEbk6WXFwHquWBLKszyWVdu4GigSpHRDFkqY4AjmI5rd+EFg1cDEePkovk/YOI4MDWn3vVvfuTWasrMiXkjzYofL/XiJ2Tl7VbZQVp6GpeuApZYoPMu4VA=,iv:WMnsZQVTJznFtTS7ZUxz+ChS68dKg+QiCswJ7H4PEys=,tag:1GzfkX2vUBRlZ5l/I2ujDQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2