apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore
    namespace: observability
    labels:
        app.kubernetes.io/managed-by: flux
        app.kubernetes.io/part-of: thanos
type: Opaque
stringData:
    objstore.yml: ENC[AES256_GCM,data:tYFp8WhDxMSy6IONoaAaD+be835ZBbiGLf+o/VOc8qlC3RLKepLFTUnWs2+j64TUQWPITJNSa5TKBrolqxyRdgU7wXN/boml1TB4OL3+p5OHZAZpGsbA2P2tGLgDpqKKEDHC4AtVBE6G3hMLAPFoi2lK2biTaBPlWUoEl78q/kBVPHSt/6Yn4y0dUBMnyJL6VQeG+zjDogVNDoj2bmtU0FteN0xN5WOt9JlEOhWWL0hdwmQh+RJFkwszMa801NlEkQ9G0zNrThOGNjC4VlFjx17c2MY/07aG2AbwbSt2hnIjhxWAiqwNe7E=,iv:LxwJKyEaO8wN9BZ6pQdkP20MlBKJKTfFYs11DAFqe6o=,tag:i46Yi4coiW0SjxckOMD0xA==,type:str]
sops:
    age:
        - recipient: age15zxr0z8cd6dqzqh3g7f8puzqwgn0f30qgrwfx26c32wljlzr9dns0ejad4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMN2JUQlY3MU0vWDdIWGh4
            QVlPRVIxVksxZXplTDMrMU1VZm5COFdORmlBCjVWdzdza0xYNlBDWklFRWw0ZXB0
            OVZhSTRqYVZjbUVHYWh2QmNMY25VTUEKLS0tIGc1TnBDU3VraVFkUFV6L1ZwZVg2
            NlVYdzB5THZLMmNGV3huV0dmSlBhbkkKM+hMcrzVpeNfMUPqtdXlkfY351LQQNCo
            yAa023/SXE9n8WEJI/fCiR4jSivFD9o83tmo9lmRndJlf/Y9HvCsqA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1h2kyl30pm90tkdz20ertu73pf94chkvfj44w755uzz7vswzqtq4s0vxgct
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1N2tiZlFLa21EZ21tZFBs
            c1cvaUJ0c211bzl5cHBvTGpQMmZIYy9wckJ3CkVVZ0YvemV3ZVo2L0kxZ0FWeXNj
            emhKWFdkWlhTdGU1R0V0emVHUXFKdHMKLS0tIDNnYldrYTdOT2l5dW1EZE5qYmRC
            UVpUMnVuYTR5ZnByL2lnRGlqTWROWW8K/HoE0mJmbO/KeXNGx0jwtHIShd4jZRkE
            E2/HH08biqAhAx2oM0EQlPCEJ6QE1sRX73egsTc0OmyIKncDy/rzmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-17T02:58:46Z"
    mac: ENC[AES256_GCM,data:mMaKNE6b7SThUjmP8XJPou51YKkMBJr17Xy51tebmUwqCl/PaI+itZGzr10Th3IKsShqfMHTJqLTEZO8WrHIKF9bKoqNRf13tv6hATZ0pz3svLIA0vMzMzN9HRBdaBZyO12MJW8In8BwPXf0xK4nFYw0lFQaQxDOLjTFI6vPWU4=,iv:HLAMFxHyU7X9ePyWtgJIjt+PyPMGj5i8KUlbV53JpTI=,tag:JLzKd1nELQPQbVlFOAhMRg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2