apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-state-metrics
  namespace: observability
spec:
  interval: 10m
  releaseName: kube-state-metrics
  chart:
    spec:
      chart: kube-state-metrics
      version: "0.1.0"
      sourceRef:
        kind: HelmRepository
        name: lab-charts
        namespace: flux-system
      interval: 10m
  install:
    createNamespace: false
    remediation: {retries: 3}
  upgrade:
    remediation: {retries: 3}
  targetNamespace: observability
  values:
    kube-state-metrics:
      replicas: 1
      image:
        registry: registry.k8s.io
        repository: kube-state-metrics/kube-state-metrics
        tag: "v2.15.0"
        sha: "sha256:db384bf43222b066c378e77027a675d4cd9911107adba46c2922b3a55e10d6fb"
      service:
        type: ClusterIP
        port: 8080
      prometheus:
        monitor:
          enabled: false
      metricLabelsAllowlist: []
      metricAnnotationsAllowList: []
      resources:
        requests: {cpu: 25m, memory: 128Mi}
        limits: {memory: 256Mi}
      securityContext:
        enabled: true
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        seccompProfile: {type: RuntimeDefault}
      containerSecurityContext:
        allowPrivilegeEscalation: false
        capabilities: {drop: [ALL]}
        readOnlyRootFilesystem: true
