apiVersion: v1
kind: Secret
metadata:
  name: lab-ca-bundle
  namespace: istio-ingress
type: Opaque
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJwVENDQVV1Z0F3SUJBZ0lVRXRkV0pLN0tBNlFhSml0UlY4ajBSU0k2YzZnd0NnWUlLb1pJemowRUF3SXcKSURFZU1Cd0dBMVVFQXd3VloyRnllWE10YkdGaUlHbHVkR1Z5Ym1Gc0lFTkJNQjRYRFRJMk1EZ3dPREEyTWpreQpORm9YRFRNMk1EZ3dOVEEyTWpreU5Gb3dJREVlTUJ3R0ExVUVBd3dWWjJGeWVYTXRiR0ZpSUdsdWRHVnlibUZzCklFTkJNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBEQVFjRFFnQUU2RFRFK1N0cEFGc2FTVnMyd2p1UDFReDAKd2NZRVhoQ1VyVWlFdEZDQ0hSN2hFaU9ldjRtelRqTk9UWnlnTmNmYWVDSTV1d25ZeWN4SlpsM1lGNFV1WWFOagpNR0V3SFFZRFZSME9CQllFRkRRMmJPQ2V1dENreVFQZU1oUVYzUFJWL2YzRk1COEdBMVVkSXdRWU1CYUFGRFEyCmJPQ2V1dENreVFQZU1oUVYzUFJWL2YzRk1BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0RnWURWUjBQQVFIL0JBUUQKQWdFR01Bb0dDQ3FHU000OUJBTUNBMGdBTUVVQ0lFU1hhVUhqVHc0Wnp0T3lBTVcxZjZtQzFJenhvUCtNbnozdApnbGlsTkRNRkFpRUFvclN0Lzd6MzUrMStnV2puUloveGlBOWNreHF2a1dlS3NMdlpSVTdHWDVRPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
