apiVersion: v1
kind: Secret
metadata:
    name: lab-ca-root
    namespace: cert-manager
    annotations:
        platform.garys-lab.io/plaintext-sha256: a5458ac79ec28919c387f7927b962ca8abb0d9cfd6ffe099d83155be8be0122e
type: kubernetes.io/tls
data:
    tls.crt: ENC[AES256_GCM,data:WbdwyBjhj7r3QsEZizzw9R72SdcrSpbav2xkVj1F6g0tH7vmLcuvo8P7KsUtUgUekG0AEDr2Z3TfMrsw3cnfDuah1WEp+Za4Dnp1nasJzBvfSBBfY9BTmhcjApEaFFA2W6VSeYhqnUE6Ij3NJv7U6Rz5yBJ4DLMUbQ2cz5uisPBqgaD7Jx15CZo6Qz33WpDNLWLHgKb1H61bLxt44VGkshodHnM1o1rwmBfrGnw0/EAZHVsfsEpDAk6J9t1H0/S/KU7Yr8FSqkwBVG6UTVOzbE7g76nClngvRv1b1PjpagFgzO9FVGPCjZRR18q9zoDewLqmAOVqm2azVOcRovWgXt6Cn3CKh1hg8I2WUbS4cEYobQ4/sCsUEqkcjS9vXdzCQjHTqoM5x8DrsaoK/76C84Zvx/hu3zhKkuRp7B5PK2rDis8gTnniXcciZTaEVsQdNkwaGimHAyKYbqVQq6kNOkpZkC+V05QVY6Ur7PatIAiO76VBFVPgGzYKaN0X/BOzr2jVa7jYY9qchtDCHOmf/wEJKeVdpoc13T3dPvb25WK9FPsJpgh3/3GXerpUl5nfoD3UphksHgYibDYNyoYEh4sbpdnIbFrjloiA+W+QwCClSEBOPlnVknqXSAQkmnJ1Tbzv0t1BULIYll7YBclIKSrEzcNb2L6yfcLtbfy2yDctETIj9uXeRJoAtD/4UkETHTzkQJN1upHwQ4ojXGtBSOWi8AT3xekxREHndxE+KUT5i6BiI6E56E8g92wWbhEgtlZxCo8QJDNqzNosMdTKBj0UVBEXXQrA1J09gkFHpTWOBvXQSvflqefe+63hzaB7Sg0gzQ1DjtzwyyeJ5M0C/DtyMvsX3yGEw57KxkNIgdMWOCAAdwYxb9VWeIbxDrtdOTjO0HnB0LQ2BT1mxwcJoyj2DFAKa7uU5bESqZJoUbm32hPpcQ9MmLIEo9lohYYx76t0rf+ZPPWppRMvfEREHAHveFGiju1LG4HN39xluYkpssCijqOvul0HHpBl/LqBUfG6dyHffbvubEuHmVTh3/p1FkTevJ7wDB9w3DrwjHIOauuwDAuC2jUm5lmIT3L0yM/Za5WV9g+iWM0DmS4vy9Ly6H68OYfw,iv:j5DpPnzAOd021u3C/b9xIZGalB67Dr6ujuaA56xRTNI=,tag:aS3XcrFF3qU2cT8dej09yQ==,type:str]
    tls.key: ENC[AES256_GCM,data:SemC19wH8V7EbYWjsrqsQEjE7iF3g362yyXfHcwBCu1Hj9lKSESygULsVdQFkN8LO5Clyk2h2XnGRnTbeGDIudPvYC5Ln5dGJhiAUffUquXRllIaFJuqYX7NtcQ+O1JfUh+cLT4wQBgfBYF73ssxOAS1pp3c8R7hBquyx1LXUFJgrqfl7NQlqwkJbbOEKcbLevCR6fOxcvkfZWJA9JexadkmYpGh9wthmn0OYREsn/PYW5y2QBDkoZGa4PIs5U6YTaeyQTMB54kxLov2IDUZLZhvTr9dgKu2JBmNbJ9SXNyEaTCi4QjSCHZ5WPTUo04kUW6umNK/FOP2OY2rW23wegrV6wcBKduTOCPtHDxdtRVOPTTWWXobhdQONM9iNXBTPgEpdYvvprRhuZlH4MTlS6uD7lh9EqT+RWFZQIBMS40=,iv:8SiHtCghjmqueLQ8CfLF1mWsjmGefGqld3CrjyRo8cM=,tag:lnRVwPIrE1Gvcw7tLp30jg==,type:str]
sops:
    age:
        - recipient: age15zxr0z8cd6dqzqh3g7f8puzqwgn0f30qgrwfx26c32wljlzr9dns0ejad4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4T01FNlJ2ZytXYzd6OFdS
            aEFieUpyT3FWcWJEMEIzUk91Ym05Y3lyVUFNCnJML285YmgvNzRPT25DYXZReVhz
            T2hod3BTOUl2NWRrVENXbE1JbllZRE0KLS0tIHB3R1BFS3RobjVWbGRLKzBhME1l
            bGJhc0NseVUrbFpLenQwZmVrNlJCNWcKr4wUaMtD2uV8rhiGxmqZ0doGQu+BuxO0
            leSkymqMN1BFaYPEk6OhQRrjsGipSwbAJdSq5ivv2ABrk0UP85s2JA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1h2kyl30pm90tkdz20ertu73pf94chkvfj44w755uzz7vswzqtq4s0vxgct
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3a0hPYjhGbWtzSWlzUlF6
            S1B6VHJlL1dDbTlVbTdyeXdjZDRyTFdjUHhnCkZtYkxBYXVoRUV0ZUhCUktWM28r
            TDF2bkx2MVByaVlTZmhlOG5iOTRDL2MKLS0tIC8rVm5XdWU4SzRyaUtJaDl4V1U2
            ZFFpdHg4OU44QmxzNmd3R0dhUTBzKzgKY/ztyOJNG157y+t2LOZw4aEwPjjnrQb0
            rjDhJcgokp4XgLByeK0VrWowKFIZG5J9EHk/eiFbsg+qah8UldQo8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-16T21:41:03Z"
    mac: ENC[AES256_GCM,data:yMWGeQUN64HUObuaSgnARPdCvQmyQ6g6/Gu8t8sVZpsuJTSd0mK1y8L82uuHnjovpzjo0JB7stfMpp3RRBLGbccFNFvReBFcaB/9vh+4QzOhWJ+rkPArEmaf5IDoKRu2ZNwaijPVaoVzCebncwa5+OlVbxWkpq37jPxho4IuW3s=,iv:3T+vc96ST9g6yO+L9PfeAzThRb9JlagmYifwYJ+vFF4=,tag:16xP/CiR8wripow6fGYkQw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2