apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cilium
  namespace: flux-system
spec:
  interval: 1h
  url: https://helm.cilium.io
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: openstack-cloud-controller-manager
  namespace: flux-system
spec:
  interval: 1h
  url: https://kubernetes.github.io/cloud-provider-openstack
