apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-variables
  namespace: flux-system
  labels:
    app.kubernetes.io/managed-by: flux
    app.kubernetes.io/part-of: platform
    platform.garys-lab.io/cluster-group: k01
    reconcile.fluxcd.io/watch: Enabled
data:
  CLUSTER_NAME: "edge-w"
  CLUSTER_ROLE: "edge"
  CLUSTER_GROUP: "k01"
  CLUSTER_ENVIRONMENT: "dw"
  CLUSTER_DOMAIN: "cluster.local"
  APPLICATION_DNS_DOMAIN: "edge-w.int.garys-lab.io"
  APPLICATION_DNS_WILDCARD: "*.edge-w.int.garys-lab.io"
  INGRESS_FQDN: "ingress.edge-w.int.garys-lab.io"
