apiVersion: v1
kind: Secret
metadata:
    name: lab-ca-root
    namespace: cert-manager
    annotations:
        platform.garys-lab.io/plaintext-sha256: a5458ac79ec28919c387f7927b962ca8abb0d9cfd6ffe099d83155be8be0122e
type: kubernetes.io/tls
data:
    tls.crt: ENC[AES256_GCM,data:u8ImvAoX0dlROadAaA8ue7cvLdVjdixyjG+7nagkyv5DwmMXoxU77/cJk0/5edhwPoP3sUzIzwLAxj9vvG2QvgIZTpXShfDxCenKvYp6HB6CrhTw4mxnXBr4OXP39AP62Sq9U0QyDDoZrxq9Oo4cgC/b6g3qaTTzoczkmMttO3+qXne3huu6yGd5+zE8gQBCFfDSamKZTYMQd9SitQ8wiQYYSRRpTbQZwfGL/0JgYMN/nS2gl2z3csdbfTRoDs3om+wOmgzEZnc+5HiH4kRGyGxAmAEv0ph6SKraG5xfeeuXmjo6XfUDLU0Y2YFGeb8G+IKpiHOR0do7k3QSNSmHnXrGMrZNul6g/+kvedwVLbfMFmSk3qR2q/7gYzmbkCyh1OSzpy6er/32GM/qI1c1q99qeQ0+w3csV28kX2/DO83kH/XAsor3ZP9WLFjgiopQSNkw3M9Gcc1U505J/JS5mlCk/jP/XEi1Ls4JlZcYiaDzyUvU2+I67b8gW9th3nKG1q+6kKH5GAegK/ApCcjQ2U1RaCVjX/adZSe7RMp2S/V7ETe5BrL3z09faeYKvdIer089qKqQh6zLWTd99aajFff4aVVjSSiV/EsoDLngGIQvGpyjHAf0rWeRvp8DoiH/X+D5kBPj6zGzCBuZ9v3K0CDWCQ2tUIZs5R7p6sk0teV0asWyDFGKRxj+TXUmRdhBUMemjUVj2bI9HfXMeJlwDo/p3xFNRN9A8jBe2MgtpMRqKL7Dt2rkITkYiaOiPl056ke8Fo5OYZ7z0oweQ3y/ouy3Uk45L1Imw+dGPSvFSxZUoo4xGs4ZHbD9KA9TFHo7vV6woSn6tERi1ED7t6pp8LtKNFcfl882Y7krQUX0HEWQfr0DOBgxejOrIVLpeHnh1ZyRIngSXuHngaLwNwnOxK3J/Jus02GzKxght8+0yTcU94UncxFPrzC4ZvyZj7dYtJN7obc8i9ivd3rOFxxut9FZMs4GynISZ9TKr3lCIy+7wDXhB4wIrKSlK3hWZVz5H1CI0i+3UXvaVUIaBXjx7trIfaU6dyWGln8g/7BM1Vnm6BY99DNTCXVEOLYbeUcs18KiP+KEyShCERusxCl38JcpxkLV1yK8,iv:lPe7wldD70H8JSGpb13O5mOCPRted5XcGcqEXSRpglg=,tag:bXa4xvBwJe4j4Url/IPcDg==,type:str]
    tls.key: ENC[AES256_GCM,data:Gx7b6Uc1JNCaO6Avq/+huYPQSHQi9inVRQUUu5D3x5oqmTxkm7PhBBvwgJR57XNI+PUSUt3mjMBLWhYtfTKuNlB/ZUhaQwq416HVtbWdAwdKz+zxWd0kpJRAnAe252x2pdJ54xG26m9YoDmnRQ2HUQg0II8UOX1HEMXvMZ0L3SIPujqQTPQUaHiyFQHWGcPMc2mit5ATfODbIY/XUD9wJvwolAbrkuhjTZX2O4VvsJlTduhHifdfJr83DYaAIyx3a6hU4nRqKOyGjnC9GM3+lP+swhcPWk/iEYmvbWh3W6wBgt2istd9rlZj7TOOquZpoFhUgJSXGX/xltSv4RIWLt7IpMZfPiGBRKs+yL6Q7blH7clrcc72hmCSqeZpiotTYt1w8aWcmwjablegMTjk7a40RNNeHRy0KMukWCcXmys=,iv:yGXkSV3qNZRuwlZdhuMGz+OOqROxCbYljeYzlQg2s3M=,tag:hV/wjJF3m5ZFJ8ft+RCfaA==,type:str]
sops:
    age:
        - recipient: age1aywe3xdhfuux5lk54dxxvhnfyxcwjyhv573cnd2l9gp0axn689msthmd7r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpZHk0dGZCTjBhdm50bkpG
            VVRhcXBqd0VGa1BINU5teW9KRTlwQ0ZxMWxJCnNRMzlqZlF1WVd6aDRYRDhBL3dG
            eHN6bGhENnIwZ0lTY0JVT1VjbzFPdzQKLS0tIFVtUFJaS3lhODJtbERYV1N0eS9B
            TDJLbHJycmM0c0xWLzNoWitZS0xPMk0KLI+E8D34NOFa3mvyspKDx3uejHvpj8BB
            BkxR32KHhYfZSEn6BKbdxscBt2R8CoIUnnCjzbA9e8ABtRhPT346jw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1h2kyl30pm90tkdz20ertu73pf94chkvfj44w755uzz7vswzqtq4s0vxgct
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrcWRBdkVZZVo5b3BJUGt6
            MUU4L1YwcU9EMUFtdWkycFRnQ1BlWEdablRNCmtYajd0Nm1Zc2pPOGlFWTlINytw
            alhGWElqZFd0K3hnWElXMzRkRGNFdzgKLS0tIEFUSUVCUW1IeVdsaUZXS3c5SEY2
            VzZocTdxREQwOEpZYmNYQlZVYnd2ZG8KmcpA8JY/jrBOFR4Ie1UmihVrKMDYGWBH
            dFU/UcUNJ3WdFK7lG2U4fTit8tdo7sT97LebPJlY/PJORr9hO/7BeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-09T22:00:19Z"
    mac: ENC[AES256_GCM,data:X5n+TkA050tIq8+lovI3z/jOuXShhqEgKbBIIeYeMTjLV/HnzdCvP12fnGi82ByG1d4HVUtCiEfkzI8gHvI5XJ25TlBXTK9wKg6sC57OGt7WgpYKfdYxElXFpwj6xGIJ00954Bman+KLcJD47EtqohRc+i/K8fPqmYfj5UAu/c4=,iv:nElJvWRZfKtYfWWn8GHgkHDTsbdIiDAjgC2hE1OpiZM=,tag:yHGUsWum0sQ2tUVxvAjnHQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2