apiVersion: v1
kind: Secret
metadata:
    name: lab-ca-root
    namespace: cert-manager
    annotations:
        platform.garys-lab.io/plaintext-sha256: a5458ac79ec28919c387f7927b962ca8abb0d9cfd6ffe099d83155be8be0122e
type: kubernetes.io/tls
data:
    tls.crt: ENC[AES256_GCM,data:YTaKiDdxXI6Lg74Wi/AI0JrecSWl9LfiD/h9NnH3bUKarFk1nF22gtgJUqoBqzixZg4cbbek2EHDMsyqPqws/payIxnrVR3B0v/E8LBBl/Ar5Vz2bCyCgIgKyLIhLMK6/mOGn3ThFqVmqo/A1/wXNObcLhW1ohIy5+UXDREupIeEoo1CvbhageSh/4j6NRHDju8m7FSChDWGUcjRoHKfrB2BJydwnyaEQfGSDoYotnbOSKbCBbTWzv4VO5DqC4IP/8vpbn00e3238j2stJt1Hp9Q2Djf0X8jnrHvLC+gtdf+y8V1D5Xtu5XG7wAaLheqwuBO5fc76E36k/TwAgPZ2WMocJ7oBNJcyDYjNwdIvfmPkE0iGivGNE+6hiRRlqpqfP6n05ecQ4VxkFoexQC6FmRNgmr2fYTSQJh68K9oBsg811d3MGeoPH2k2P4a3aLbLwCfr1IWBBLXmlFApiElrx1usAaOU60YKNpsixM/6BeHjjsM2Fd6mU6OKaOOu3ikHONSLoGRpD6J9lNCduZ8adXRUJMoS6ov6AD3sELvyBoeSQISAYoG5MP0VXODtBIKVvE+n/zUlNKd42ao82n7B0qD7yToEYNZuyHBQctXY065T9+KeJsjQmsDckQW0j8PjMvtp7dbw4lam9eCcU6Kb8t7xrPtv7J6yJvappHPxRCVNBX5xCkAsASS1CXveGWzFtLMerErAgG0Jrnywdy09tmbbLgkvEvJ1z0mwtMT5bfdYGOpWwkHZzYmep3WICTThyLCLR4ktf5Mra6rQXmt1DexgGYTdmZg3Oe63/xDgGTQKfzm0nlnaERc86hLixsIsTXwtGk/lO9W9xb9Kp6Nag+duCLKziuyydfOc1Dy/nvcAq9o1kDFpOsVp0KwrMpYearE/5I90DBb4W7yRgd345r35Dj5499kogtiSOx31UzHXWZarMH/nWp+C4PCSJXpfBF+bRcdswCHlHqXovVJlybcQOXJ0uzdurcJD1/dxppzSgSPXFvZ/8goVyOv5doKfOyjljhe2LZ0IR4UDXSM+ITp8jjbhlnYl2go19tg67kp0VINZcykn884PQ2oRJq3ROwQoYperwJaipsFXkPid6Hl1I3vceAu,iv:c32MUDqfErDBwIUt59Q5+dhwddg9psnBI74Go9AIODY=,tag:JRbSywWFw3Mk9RLW6KW5Zg==,type:str]
    tls.key: ENC[AES256_GCM,data:7rMNP1tLCTG2xhEtQDJIaV07BYp/qp2t9KIUHpYo5U0FuYmkrPtT2RYNcv4vCEAuy3lPY618SarcQnaGDGe3e9MDjfZVbqmnWo979fmJW81bQ10NZ+dY4by85l/IjttTTJxsZDpVQjJTb/zjcV7gj6IMps5QDXfjQn6T8HbDE0bhCG5QcWpqpyrs57Ol2rP5tgFLNzKtQtRD+aGXtwcUdhffTUasK2vLGhtSoBAIEne6xNn0z8mk3pAKXRTjAC4xD7Aet2hcqOLs2p6VQmpzjiuDmf2+KyvbOCdPIx4eLXRhuoz/ZpkRK5xD87qHcvY9tUsDAz4kj37DMGLnL8vevzIolgBNNFp8mMo82C0pGVVsd+B12ZYdsnD/D0pJ6FGzb210FyPpqNa533b9h6frAtPKpPDoy4Po2bdXu2cCMaU=,iv:bW0YsXCk8qwGVLr46/yThWbAeK+KzBiT5/2bmkHUsdI=,tag:X2/T2FSHjYinUlGazKTKqg==,type:str]
sops:
    age:
        - recipient: age1aywe3xdhfuux5lk54dxxvhnfyxcwjyhv573cnd2l9gp0axn689msthmd7r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlQXlKdmh0dUFPN09vbHBD
            RXhiTU0wcERQdjBFMHVpNitlbGMzL0VKd3dFCmhKaXc0d0llZUxUaWdrUlRIVXh3
            aVFmSVN0U09LZEtxMkRqY2hiOGxzN2cKLS0tIFlmb1dqcWhPdTUrS2RRSDk0VHdE
            L3NHYnM0dVBGUStFYUgyNTV6cERuTTQKB4Hq3k0nPAk54lFs7uPsqkS4wjJi7O4J
            F/U1HfTmofzCWEk4PYFb9dXWzbVgyGr8vjgcm9GWZAFGWahCqX/4mw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1h2kyl30pm90tkdz20ertu73pf94chkvfj44w755uzz7vswzqtq4s0vxgct
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4TkRoTkdmMHZya2o3YjdF
            OEVVUnQ5eTlqbmI1RTVOQ0FjaHNHOG8venpNCmxxYnRXZGlZVkZxS1JDUkJ4Qi9U
            SEdBUVJ3OGFQczJuNitmRGY5N0o2b28KLS0tIDZYUEEwekttZXYzRWV2c21DSFhZ
            dVRFNlJjTW42d1N5N2JGbzZMYWg1N1kKr4D1FKm4oWcgd9w7pt658rWBuGFP9ymt
            9gh+54W3p3HKNXQtsIyl07ks0X9v2wt562BWO85N9xGoZcqsX037DA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-12T05:35:55Z"
    mac: ENC[AES256_GCM,data:ITEPbrG6iQ6z54sltADwJP11jGOPQZCzgLvbrfAB0KYHRCM4yohwXt2fr87Si4pVjsC4AWqZZ+BANd3BIdot640e6gtzZQ7lyYmeIMlgMHN4I2wAZBDaDopcuWkAgb9a0241D0CDzNPGUhB+hdOyxQFiTdZryKphdJWM/h7GJ/k=,iv:USI/b5+gR7mvpvxTf656F0szvNTFV2CRpstIctT8OHM=,tag:3Ubsh1bomlK1GRCaEJyCCg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2