apiVersion: v1
kind: Secret
metadata:
    name: lab-ca-root
    namespace: cert-manager
    annotations:
        platform.garys-lab.io/plaintext-sha256: a5458ac79ec28919c387f7927b962ca8abb0d9cfd6ffe099d83155be8be0122e
type: kubernetes.io/tls
data:
    tls.crt: ENC[AES256_GCM,data:PvkaQtHF/k8q84LsmyPwxeFXslkzdGryE8VM8a2/4h/m8ssRbEFgsfu1qAfRSvrgY1kCovZUcNw6ZN6YTqmneYBxuJKw6AEiXFiCkdrbq1O7EbztWiegop9YlYqNa+e/jiLyOvvJHaVOQwUvm5j/6Y4gKpxJA1H4rAAmVejy4U7JMVqe0opL423oRjlPUSNJSH0v9uOvdjOzT7ngMpl3+Vk3CEy155zKG5s3+Wk0nZ0WGdf+NmkRODFSQPX0yvT/G7JkdxJf2sQQJ/uwuvXJBXh34ajW2JrToe7Sk52GIWxOzlqAXeFvc0+Ag75ztENMvnf6pJCSxifRlL5EDKqLtXLJE4TC3iuSw1Lr+RjLiXxw2cRcceop/8+e3uGR1VieR4sEPBuyhSacwwmj1cO1WWswh9G8YmU+JfCKJT8Qg65VemnjQ093JUJKn50UyuGGispuHPMDDj60k0EExVaN5N7lZfKh8pPTxnJn0F7KH0T0LYd2NhBXt+XYZK3q7MYNwl/nmm8lvO9Xwy9ccSCTh3MZjQ+fx57h/4zwsvcmRHl8GO/Bj8QWAJDfPFYnZiRpSvUzNA7cwraoHBAxBOWFSg2KtMWfjtzlNPYZOqjywajY8VevZfDA5A5zbGmoBf5NzM8ECx94FgD+GMXStRN9SKuDPNEbA0/B7JGzFAt4i7mvCg/pZ8wYQs3A3Xbd1IF4z9MpWoe2Lf2FYN31c/OXlZcZA/bFj/1iGGEWwP32cgY+3CkmuqrFHPbxdeJbFFgSWnSRrpCefVggljqidgHBbxuy0+PYaS6fdhpe4vubzTFqxUdAaNxJetgKFey9JKHxxKDoguGEauInDAtxM18YsTMQj7PQspQxeJzk7hUjK+JTULDxd1qknWkryXz6N4yMXTdvzMvzExblNK4w3/k+OcZRUl+tIqTVDTLD98EHXLjPgg5usHq4Q51I8assFP+Vg4UTSKYClv3bkKxVRsbWNYx54mMJHwKMIGp2fFR6RzVv5tENp2fSchksyhWJwK2HRM114mP7miS+GjZejCRkiHjOFOcSXwmZUfhV8xfs4QgVNO/hGOEIAA8j2YKMYYu1nkcXzayC+paReOp1EDIhsXV2LzCoBSoZ,iv:uQtqNhDwZxhz3bX+ifMcHy1zKlPVDJlxusTK1bX+wFI=,tag:5wuFXCZzIih0PRuCJ7XjBA==,type:str]
    tls.key: ENC[AES256_GCM,data:tpmUrXxuzVrM72ogYVRxzh2QsNEzmSbslzLALvcptLWiz97OU//8dUkICUN1+ThDyJY+vRYh0Tw50eIbXoHK1iDVZht6Qy9z7ZTM5IcUtfgIKQFYwmaZUsXZkGeibHEKg2Dqs/V/oYJjzwZOhQbzLNTx3Wds8p6aQOWv1KSeRS4jf6VCukT4Ye75Bf5I9iTp8u80JQOpz4huTgcSH2w82ooATnxcLbO+/PP5thZT8uAS0uq0pBdNvfLzhoZf8BoPwHlbowYk+PhGlFs8BNP2p3VqOBAQ+p3WqrqrOirjfQD8BN5taCDEcMCFWfcoMQ7KBGKmONDDwBWMjyiSgAVMgihhZQ6recS0C46QzKSpiEanjsO0u7oFWgdWR7izPmPSUxapgYgma+ZrQAjuJ2fjD+uLY37H/uH80VkUkb8lppo=,iv:1kwCzyNGZWNXtXNXBq82Cv3U/mBYAB6w/oOu6ugS90c=,tag:ZsDqVbwZhwhf6Qt8dicMtw==,type:str]
sops:
    age:
        - recipient: age1aywe3xdhfuux5lk54dxxvhnfyxcwjyhv573cnd2l9gp0axn689msthmd7r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkaUMwWGZ1QmVaOFBYL0ZF
            cWp4QWhucXVaRTdWNGI0ZGlxQkJjbUdNQjNvClhSMXNmMUxMUThySTVLU1lLdWR5
            dUlialVQelhSdmdBdjBZb1hERGFzeE0KLS0tIHEzcDd0dE8wL2xRWDRuQnN4NlNq
            QThXRzBobEFodjlhR01BOU5CZ3h0TVkKlSkiETpkHk8eCOFZ1aT8IiWkRIA79ibL
            dFgaznhp4iOafuMDwU0ldfwzcc2+QhdbEZ4v6lQnW+mPK+qzljEHsA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1h2kyl30pm90tkdz20ertu73pf94chkvfj44w755uzz7vswzqtq4s0vxgct
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ZE5QWFdPUW0zTnM0eGFL
            OGozZVllU2w4UnFYVFlvNkFyUVljYU5VNmlNCmtZNDE3eTN5cldSSUcvS1VsU2ls
            bWp4dWpKd3lvZmllbUtDdFg1aFRhNFkKLS0tIFNBMGdmdHhPcm4rajVGM3BEMzRi
            ck1Od2FwUXd4RGE0Z3FsN2treVNlencK8dVi3KqREa+LEko2Kfa3wkusDYnWsNx4
            AYtCisf8jLPTGPvdPdY5/UV1Wv7AqXMvrf98FOSZu+jWoEIHVMMABg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-19T04:55:10Z"
    mac: ENC[AES256_GCM,data:JgDWkLhBdinAy4I6+n0rXyS2BifDf6Rqfg0PZiR2/p/oFASm3iNz18FflgXCnDfLITFDciemxiJgX4QkL8lBfE/M9ZgKE9opaZQbWzga2FnOuB+JQnGKPGmLRjYb6r7cEl/Cd0RdlvuKDnCelNXGIPpQyn83gPqfusysirX7yOc=,iv:FFvorx1mAAj7c+YbQrO+FhWLe+E4Q2UsJLWDlT1QqX4=,tag:IO9S9QD+/2anx90gJlucRA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2