apiVersion: v1
kind: Secret
metadata:
    name: external-dns-openstack
    namespace: external-dns
    annotations:
        platform.garys-lab.io/plaintext-sha256: 2ab63564df382b33059aa96d152e656f5c832d29ed63373e4dbbe10b3b5d1bd3
type: Opaque
data:
    clouds.yaml: ENC[AES256_GCM,data:kujDz8vmbTJWxktPQuZNCOYPTvfuslW6V4ypeX6zt3r9B5mqaqQ9M7OU1At94antScCi443EbwYjTRJ5ESoYlwgQJLrcBVWTq2xl7haMdYcHhAkk2rzWyJz5jFOvKmyGidO7s6CxzsiVxrniMVZqFjN9Tc3FeEC1rDDO17NXM8aE9UP4hQHUPd8TkGFishpUfoBSAlCKcsaqOBMI4RstS2p1I8/GXWlI2arvrYPKhW2PerG6604gCPHT8VVs66s9wSU57u1ZXNDuuxtB7g1x/PJYwodfF+WdM+ebQ40Stfe+rZWDxj4qhgwGl0kFK8TX7W3UBqbovteP8gtLR4XtjJV4Ul0CSiQ3AJrmZR2TAcIZuKztQm/1nTfhpG+zJwtHs+LCJzti2VEbT1Nqqa5/6nsISjxjMrx/3/M6yW/wiQNymF444KKpp8WDAIMpNwPwepYqSGVcwPPhA2sERE1/lCTkAYAHyN7dDGv59VthVbCdNHSxvdZYSnKbUZfRF0kBPVizGoLUuztPaecPH3LCKm0C2u17PJvj2rzU1WMsXreSD5FN5TcMEmV4U1gTv0YOdY3UV+J03jcu0acHiZjxsrxUuyK4LRk6LJOqhzMGUF2s6lqNbHxfIGnirbUf5LHl7Wn6L9RNrufDpxAG0kWd2Udouy39E+LnWntzddYaifMdr1sgTjsVfGEVbncDOzXv4pbqKGwyaM2x5vqFdAQtlDOCoNLD071fzMaozRvlQYuxOETUvu4jRy9jQCitz4F1f1VQms5kEUfbeyZC+UmyTUT9rIz9YJp65LUAcg2x9EtyKb2wkRFbrUS7D01gk7LDGdAnDGX0hhb/ZwGW0ISV7GfPbStKmGIeWV8DLDVMWDMaBxc37YM0q4wDIRE3ZtWMNIQvlw==,iv:hUSZ3puttnj13Z0wq1wc5HIAQThc2tWYKQ4YrnXLeVE=,tag:DYE5glTRaHEW544wNkv9cg==,type:str]
sops:
    age:
        - recipient: age17ru9ns7l65qdca574qd8ve80czz48cvjjd4pltcprfp0ptdefvwq2t62kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlVzVDak9kVlE1NTVUVEx4
            dXlIWGVWMVFEVlZMRytQTjJ6N2dKbVg4TkV3ClBHaWxEdzh3S0xCNTdEWFZyKzZs
            RTNoM0l5aHhHMXRrcGliTmxqYm5FVUkKLS0tIER4WVVuWmMrazY2Wnp0dUxhRVJ0
            ZnVOWEUwTzVzenhPcEh3MXp3VVNHZkEKrJ+DMGKrEkUh+OVwwyZDZmhzJYAoCuNx
            8424BagWiLzeUgcMzBog4FqFaFPLDSVwKrLeDEgzvrTiMXPF+HgvQg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1h2kyl30pm90tkdz20ertu73pf94chkvfj44w755uzz7vswzqtq4s0vxgct
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2eTY1WU91RTNEUnErZ1BQ
            R3Z0d1VZWHp4bVBBdm9EeUllZ3ZSMUluNUVBCitpT29iZzBkVituUk5GTkJRcFIz
            WlI4STI4bml6TE5wK1NjK2FmQUFoclUKLS0tIGt0R2FET0ZJVVdOeHlYOXRKSDVG
            eDdNODU4bUV2alZZeFBOT3RxelkvaEUK3t25tbTQt/ABFFzPln24J7389Wjbbcyx
            USJXJV3GfctryVdWYYZTyhc4UdWn02RUB8AFIsUoFkwyTcFdVijVRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-09T06:38:18Z"
    mac: ENC[AES256_GCM,data:logxTAb8RKTr+CBfuxm8QJP9KewDYjVFbHscrn4XfqNF+aC8d5VH1dLX7JpGshVhMtLBs9QNtr9Ga2yZweBk0eZ7iwJJFyuVwmN1p/hxZtWB70sgNqiXOOuwM9CFlpbO5DAaMPCbyQwNn89Z126PHys7Okfd6DwHoj8w4VGDEMI=,iv:VBmwvRftqIRPZ8Ox4dbBRMsxl5UbIHQW6sp6gK7Rc+I=,tag:s2SOQ22CIVSYev9z6XTN6Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
