apiVersion: v1
kind: Secret
metadata:
    name: external-dns-openstack
    namespace: external-dns
    annotations:
        platform.garys-lab.io/plaintext-sha256: 2ab63564df382b33059aa96d152e656f5c832d29ed63373e4dbbe10b3b5d1bd3
type: Opaque
data:
    clouds.yaml: ENC[AES256_GCM,data:N6bcLLt86nLIzgH4gs1SzdrsM2wHJyM+25+LbWL/iLNQbWtq4AW3tq0aw1ejSTSPrWlupRUtWnIelQnxX4mnFiQoofcKc5nKIkxcy38LF756vSAW5FJnVVMhDxicAIb+mVgaph21QqNh89hEw8zKRmu+PMYzrr1dwXM4ySfawj5Hy4NM2VOq9mhPOmCCp8SzF5pGaRv98+Jg4TgXtVzG8TdXkkom73HCJhwoNOen6hEIEwLS0EgN2dE1gzhdldNFfGuYNI5RoVgMEEwpH/P6ad1p4lwcGqOuwKoR9wQngJuz5QKrv3b7KbOJHyfgJz+yKQBweXC+TERBtJWlp8yDZnRLDa5v6lcngJ/UBzPC3XpGpUrn3b7BBKAG4m+vn2Wun/6uWT9Ny1iItiueBRceYESRDEvLg/5fGvAo8Ib7A7gMyFl5NslIH5aXxLLQI0mEXWPVHxGmjD2wjOi9WTY7pI+m1QmiWBwq3f8kl/qPRklewPlfE+XUzcqEbhSSsXNMyBtuR7SCwbo8vgOHVVZKjGjuc3G5uEDoOaZoDGQclkcJUl+FRTbflX57/R3Yu1ZtxiZm89gtgL84BfrpmHTw3B2H55zrHh6hnJXm+SFRG+XX1SOZSvWz+s6DLMlIhUzxY+eRCNYl+iOrligZM0/tGBEHnUgBzaDVHr/PFJTk0biedxAIsDxKI0PYy21dkyrF9qatLm7km1uNzRUk7KG3jluzWm7uN5zOTux00rar6USCGUMmQsNZuJnpSwpkh2fpH4ePjfIuqCV94x/dtzHWq2EcagETga+ZzJQuESE0GhqAYl/4/y3K3JNdfDqoKf4wE7jB0VGxhHTygqPLrrP0KIxW1mSffFnsh1wVuHxoT4CYZHexz8o4jATCDILL/okYhM06eQ==,iv:WEvxGPDfvFTPTD5MVdtCCgULCGV7IsdsZ6bjo/O8IAA=,tag:/KgK4IHsF3qRZ7KiEZoBCQ==,type:str]
sops:
    age:
        - recipient: age17ru9ns7l65qdca574qd8ve80czz48cvjjd4pltcprfp0ptdefvwq2t62kr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEaUN5VWwySmtXMTZzcWVI
            VTdFSzRXWXFKejh1ekVzWEtPRUloTFM5dzE0CkFYYnJsUlc4aDVpc3FId2NGcGdN
            Q2wvcUZsTUQ3YS82cGJRMkpYaDZaWUEKLS0tIHhXWDhuYWo5NkRCMUFCTHBlZm81
            R0lQcTZ1MVZWYUoxb1pMNjNObDdLUUEK0B8YfCEubHM8wpqacv38FKdgh8N0jAxZ
            sfdTXgRQvEMv55LQPOnw4KEyOVfgd4O8hRH53UjjYAPknqHkvSxEfA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1h2kyl30pm90tkdz20ertu73pf94chkvfj44w755uzz7vswzqtq4s0vxgct
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBybkRicmhLdHE1ZGpwV0hJ
            eGVxclE0STFodk9ZYUFEMHlZUUNCWHB6c1NvCkJ1YlN3QmxEUDZlK2YvdVp0NktS
            aWxoNlZhMmVxYjJkQkFKdTI0RldmbWMKLS0tIFVNNXJXaVZTeUpuODNGZXZ6R094
            eklGVEdrdjVsUithTEJNYWFxZnNpa00KRlSmQZxbdddZbwCJSr6ChjjOU2p/ly3I
            LopKeqlBq9xFdXYDWSUTxPyi8AI+0Yk9JPoUGwGX+eFH0cSWR6Qp8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-09T20:54:15Z"
    mac: ENC[AES256_GCM,data:IPmAiG04oTITvJYciPq5pha2f78GMrRi/Hyic3x91MMmxazFbTEejY6qunKe4bWgv0M+rp1GeMkYaWl1WYwjxVFL8efu+3pz/nv/e705HYXojIpka5UFCQ7j5hRRmisHyzxt/eEUF1U8kWjfbYX2ZU/srIfc6vbeaO9NNV/fsng=,iv:WRAGtvIizCNtqWiURhQ/k1h6LMK6lEid4GJHfRxjlOY=,tag:+faXH7NkD/y/lni8UtlxDg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2