apiVersion: v1
kind: Secret
metadata:
    name: lab-ca-root
    namespace: cert-manager
    annotations:
        platform.garys-lab.io/plaintext-sha256: a5458ac79ec28919c387f7927b962ca8abb0d9cfd6ffe099d83155be8be0122e
type: kubernetes.io/tls
data:
    tls.crt: ENC[AES256_GCM,data:3zzAr1x1gTweYD7G3prD1eFmjx3KRb6ZBbkzgU3F486h60TAB9p/Y+iXTcB3dghMSnXeNkZ7O9qUiixJSTTzoUFKQQ3stXPRLKZCzC99mv5K2bFU9Ivg/wIJmV0GR49v6v7u/LVvmEtZ8Q8WFJj1WjRh9ukmSh3E+W3v2UYn1MxYZNo90DyUqH6s9p3GeEaoZYGkBbTRoZDPaTkWuTSfEgsrPpbzHj/NiK0iY/H3qaSdIMApsIjK/XsD70jrn+yuKwXdDmYwiBv3YQnZdOke2G4dxG7J+DK61w6iEk9vq3psyHmFPFVUetiKq9pULAvH02iqXeOkHqSDI1dgBHpgKUoESHe2xBDJsprWs9fqPTApq8BB8236Y7SP6YIkK+cvkaNxR3kVdyHzj1o4Lt14wldAKvpveVemOQYM8MBsS8qDywUJhVm04bmFw5Irozk88V81JPNZ3AfVmdNcRld8Yej2CEPY9YgV7bzTD3snDPelPZrPwqwxIpnWVpSqW29IFGH9YNUPKOGShbQvhOVr02YyGAJu5AqU8DFooSP0iAbxXNUOsF/5CDqkJUV2xOXZ73VML/io9OMM9al/uab9NEICjTCDDy2DDF93ajjRz4j49N3fMEkcVBvLiIeLJXUshWcYRXzQ+B/aPleAPblTB+N0RzYNKEC4USnUivlwsmlhjufQg7r8P6p5VZPBUK7LyB71UNYc4yTqYxpMfx+7NfUfrV4NVA9NDqHyMqCQ9Bg5KvH2CfWBoaIQA9HhDgMniW91n1W3xGtKeqvRhLEIlZ9t+2vSIGTxlvjCX4Ab/4SfSc9S1SErhhIn2kEQkKUr5nJXyta6/koI2NPVnpdYPs6NrbwapkRe6Rsc9/YJtkEGwoum6VhAVPvGCwtfS7FwZv9WNJNcHZsqkj+pO1L6VUothRkJhgEIzEbOr8tXMOyNvU3jifM6hFlbBEiZhRQUeVBebKB5e2MkmU3S5TWw9KZFviwo5W+mVuutDu6oZgp36ZPe624gLZdVdvVzhNrEH1bX3thI6iIuP1nthCW0wlzGVY94pO8VhHDT7CgZ0kCI9C4FLoJwmvxwzXPar4nwNm5vLBPxiBQvomOdXJjESfb8QR/y3UfH,iv:jXBZ26I+X9OhxJkt57Nl8gA4T+dUOtEu23o1n5lyJDo=,tag:wLTLg8dIVFLx51Tzb40yOA==,type:str]
    tls.key: ENC[AES256_GCM,data:A9zHviBBTsY6RytYDlM3rKEo2MZVGAcq4hIe7ED5qB23yvezzzHlKjEhHEurfG2c8nRJYlZyBLX+xpxfmoDBAzzJWqtGT08uUNxVAr6/cRuR+cQ8Y191+Hs00Hfwo9XlRHa8AQSVEX6Usf8j/5BjBLCfpsk4z09DdpnT3keyjhJPa+pIAG/WwdWZE5jqp7Y3oPe2Tt9FnZetRhgncZhwMRZPkvR1DLdmZIbKitMXKYB5p4hTw24mPKSm/0SC1yYqY0QSC9Wx6pnGyGXvKnNiLqXsK5sQmqXkC2GkU0lEeoxqPo2+UkHkkSJ1DnB8awf304T7ZSv1ULKk7HMJ1BVo+2FQ6cShDkMOstbpBgbTR6i8tcj2slP9VA1BjIZ8N+W1ClOO0ufR9Yuu8RNOAHMs4wZCD8rZviHjaz3yUHdYAlU=,iv:/KNw8sO2gYXgu2uK3vxQnlriTQEaJq8MNLIrNlpi+FQ=,tag:P+TLAsR5YVS+0+6evddABQ==,type:str]
sops:
    age:
        - recipient: age1ehkefylqs2x4qc3mrs05hz2z0g4s82gscz3a7cc9lkryp490e4ysch2lkv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxUktDWU5RNWpUODBzaXVU
            SCtFUmgrbU5JU3B3M3pNaldvekt1aWErTUZnCjdHNzVmcVllUzNCTG9Gd2Q1em5T
            VGM1R2pPckg4Q0s5TlJjRlViQTlheGMKLS0tIFEvUHYwZXJPZ1d5cGxDZ2cxQ2do
            VVRPWlRBWnRHN3pja2RRczZoYXpuQjQKB+uSrzL0KyImj+/X2nwbrPeadQpQudMd
            yy3RTZOoSpOaUEH3yPpCgoqDI9K/c/mtYXNimRPlNJLcIOTDC3qnrQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1h2kyl30pm90tkdz20ertu73pf94chkvfj44w755uzz7vswzqtq4s0vxgct
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwakcxazhPak12ZlFqRlVo
            YVgxbkI3TndHZnVKZ2VyUE5iQlFIZkU0L3k0CndYYWkzcDlwMEhFVUJhcGxKa3Vn
            R0FVM09HR1hqd1FMdTNsaS9QdmdYS0EKLS0tIEYzNVVYYjN3NytPaXpTM2JvMWxB
            R2prS1pBZTJkcXhyM3Z2eEd2aDErcDQKAGT0ueHkkXVYuBQ6UAAM7k5KqO5YvL37
            Ig0YmIpVVIfra3MsLWNdq7KpRzfPhVbg9OeGctTz665CWYPRjDD+qA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-12T05:10:39Z"
    mac: ENC[AES256_GCM,data:MlGo5IALHsCET9aXLRBDiCDrfoOyQ+SNdzB8ppq+RVB4P5syXY0BGRN4Ac3rzupNvCerWK2QnR9xvGeSslZvVVg/kA0BT7U+uKAKIszrshAcp9wKM7hQvPQw1RCb0dQ76A9iYcDHpqop2NksbPyBDUeKtUlw4YoMgwsbtyfqSaQ=,iv:669ROpPY3CAYNP9iz7u6eg1gC5LoT1bBlWpZ6PLXuzE=,tag:HXqikcM/9Kuy/Mjv7IlVtQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2